### ISSUE TITLE
Retrieve frames in high quality

### ISSUE THREAD

**Issue by Hamdi-Ben-Abdallah** [whitphx/streamlit-webrtc#1047]
Hello,

Thank you for this very useful work.
I can't seem to increase the quality of the videos. Is there a solution to have high quality images?

**Comment by whitphx** [comment]
This helps?
https://discuss.streamlit.io/t/new-component-streamlit-webrtc-a-new-way-to-deal-with-real-time-media-streams/8669/74?u=whitphx 

though, ultimately, the resolution is determined under the tradeoff between the quality and frame rate/latency by the WebRTC API under the hood, as this library does not touch the deep config of it.
