### ISSUE TITLE
Installing streamlit_webrtc 

### ISSUE THREAD

**Issue by Dina-H-Alhamed** [whitphx/streamlit-webrtc#1056]
I am facing an issue using the streamlit-webrtc 

Even after installing the library with pip install streamlit_webrtc 
It show me this messeage
![E972FF02-66B0-47EC-8E81-0B6B2532B046](https://user-images.githubusercontent.com/113273339/189511091-c1c80230-d374-4d26-b5fb-583bf6115b64.jpeg)
![AC3A6F79-76F6-4FAF-976D-B127CB0C1300](https://user-images.githubusercontent.com/113273339/189511092-4184985e-2a5e-4078-8d85-d29a4a992e5a.jpeg)

**Comment by Dina-H-Alhamed** [comment]
Anyone knows why it’s not defined even that I install the library but some errors shows after entering pip install streamlit-webrtc

**Comment by manhph2211** [comment]
Hi @Dina-H-Alhamed I think following this [https://discuss.almabetter.com/t/capstone-project-facial-emotion-recognition-library-installation-problem/5886](link) should help you successfully install it!

**Comment by whitphx** [comment]
It looks like the error occurred at installing the library `netifaces`, which is a dependency of `streamlit_webrtc`.
The dependency chain is `streamlit_webrtc` -> `aiortc` -> `aioice` -> `netifaces`.

Technical memo: the dependency tree is below.
```
aiortc 1.3.2 An implementation of WebRTC and ORTC
├── aioice >=0.7.5,<0.8.0
│   ├── dnspython >=2.0.0
│   └── netifaces *
```

Then I found this package: https://pypi.org/project/aioice-no-netifaces/
Can you try it?
Install https://pypi.org/project/aioice-no-netifaces/ first, then try to install `streamlit_webrtc`.
