### ISSUE TITLE
Camera doesn't start when offline state

### ISSUE THREAD

**Issue by RoloAfrole** [whitphx/streamlit-webrtc#1119]
I'm creating a camera app that runs locally. 
Also, I want to run it even when the PC is not connected to network, but if I press the start button when the PC is not connected to network, the camera does not start and nothing is output to the log.
<img width="617" alt="camera_image" src="https://user-images.githubusercontent.com/13214003/199183279-cd5779d3-2fe4-4aee-b281-23f431da2e13.png">

Of course, the camera is displayed correctly when connected to the Internet.
Currently, when using streamlit-webrtc, we only do simple processing like the code below.
```
webrtc_streamer(
    key="image-filter",
    mode=WebRtcMode.SENDRECV,
    video_frame_callback=callback_func,
    media_stream_constraints={"video": True},
)
```

What do I need to do to make streamlit-webrtc work offline?

**Comment by whitphx** [comment]
Maybe duplicated with #485 and as it said, it depends on the browser's WebRTC implementation and sometimes it is impossible, while I can't provide the final clear answer.

**Comment by RoloAfrole** [comment]
When I verified various things, the camera did not work in the offline state on chrome.
On firefox, it was confirmed that the camera works when it is offline after connecting to the network once
