### ISSUE TITLE
hosted app fails with 'builtins.Certificate' object has no attribute '_x509'

### ISSUE THREAD

**Issue by gustavz** [whitphx/streamlit-webrtc#1163]
Hi @whitphx I got an app using your streamlit component running, thank you for your work!
It runs smoothly locally but hosted on streamlit deploy it fails with 
```
'builtins.Certificate' object has no attribute '_x509'
```
It looks like something related to `pyopenssl`. Did you see this issue yourself aswell at some point?

**Comment by gustavz** [comment]
was able to fix it with specifying all exact package versions

**Comment by g0lemXIV** [comment]
@gustavz I have the same problem with the docker connection. Could you write the packages and versions you installed?

**Comment by ychafiqui** [comment]
@gustavz I have the same problem, can you tell me exactly how did you fix it please?

**Comment by gustavz** [comment]
Sure, have a look at my project, there you find all requirements and implementations I used: https://github.com/gustavz/jaivus

**Comment by whitphx** [comment]
Thank you for the report.
It can also be fixed by upgrading streamlit-webrtc to v0.44.1 or higher.

**Comment by g0lemXIV** [comment]
@whitphx I've just updated to the 0.44.1 version, and it works. Thank you!
