### ISSUE TITLE
Camera feed not working

### ISSUE THREAD

**Issue by m-ali-awan** [whitphx/streamlit-webrtc#1176]
Hi,
I am trying to capture images in live feed using streamlit-webrtc. First, the issue was https is required, instead of http. I am testing on colab, and using npx local tunnel, I got https link. So, I was able to click on "START" button, but then Video never starts. If I select on Select Device, there it easily can show the camera video both front, back on selection. But, not once I click "START".
It gives me following errors:
```
AttributeError: 'NoneType' object has no attribute 'sendto'
AttributeError: 'NoneType' object has no attribute 'call_exception_handler'

```

Now, I saw, a lot of people asked this, and probably it is not solved. Kindly help me with this, or if it is a consistent issue, should I use something else.

Thanks

**Comment by imjking** [comment]
> 

hi, save problem 
Have you solved this problem, please！

**Comment by whitphx** [comment]
Please refer to https://github.com/whitphx/streamlit-webrtc/issues/552#issuecomment-1108781763, then re-open this issue if it doesn't cover your cases, thanks.
