### ISSUE TITLE
cannot import name 'SessionInfo' from 'streamlit.runtime.runtime'

### ISSUE THREAD

**Issue by LetianLee** [whitphx/streamlit-webrtc#1187]
`from streamlit_webrtc import webrtc_streamer` failed

![image](https://user-images.githubusercontent.com/73881739/217956351-ed9ac481-de47-40a5-8520-74f4d8478f38.png)

**Comment by whitphx** [comment]
Thanks for the report.
This bug occurs since `streamlit==1.18.0`.
Use older Streamlit versions until I release the fixed version of this extension.

**Comment by whitphx** [comment]
Dev note:
`SessionInfo` has been removed at https://github.com/streamlit/streamlit/commit/d2bfc89d7340d79e6c80d83168709419e63f7b0d#diff-84df308331455f3a8e7cea197b93f95cb257dc6ce21db238f57e0b0cae81d3d7 [between 1.17.0 and 1.18.0](https://github.com/streamlit/streamlit/compare/1.17.0...1.18.0)

**Comment by whitphx** [comment]
This should be fixed by upgrading `streamlit-webrtc` to 0.44.3 or higher.
