### ISSUE TITLE
how to forward ctx_video  to  RTMP ?

### ISSUE THREAD

**Issue by hcgprague** [whitphx/streamlit-webrtc#1214]
how to forward ctx_video  to  RTMP ?

**Comment by whitphx** [comment]
I don't know.
You can get the video/audio frames from the callbacks or the receivers, so you can pass them to the RTMP transmitter?

**Comment by hcgprague** [comment]
Yes , when extract the frames successfully .   Then it could be sent  to   RTMP://   by  ffmpeg  library.
