### ISSUE TITLE
Issue with streamlit-webrtc when deployed on cloud

### ISSUE THREAD

**Issue by TANH0165** [whitphx/streamlit-webrtc#1221]
Hi! I am trying to do a streamlit-webrtc function to link to my YOLO v8 model.

I have issue with making the function work when deployed on cloud. I have also read on the forum that other users have similar issue as me. Could you please help to look into it?

https://discuss.streamlit.io/t/inconsistent-issue-with-streamlit-webrtc-and-streamlit/39447

**Comment by whitphx** [comment]
Hi, sorry for my long off.

I fixed the problem and posted a reply to the forum thread you linked.

Thanks!
