### ISSUE TITLE
Webcam Stream not showing up

### ISSUE THREAD

**Issue by Martlgap** [whitphx/streamlit-webrtc#1254]
First of all, thank you very much for your really great work and contribution!!!

I currently need help accessing some of your demos and running my own App on the Streamlit Cloud. 

When accessing the demos and starting the webcam (after granting access) it looks like this : 
<img width="743" alt="image" src="https://github.com/whitphx/streamlit-webrtc/assets/20643017/26e56afc-ed19-46d0-8f95-55d2a8b98cde">
or 
<img width="758" alt="image" src="https://github.com/whitphx/streamlit-webrtc/assets/20643017/de98323d-2543-41e5-b3cf-5eb9512253eb">

I have written a short sample app: 
```python
import streamlit as st
from streamlit_webrtc import webrtc_streamer, WebRtcMode


# Streamlit app
st.title("DEMO APP")

# Instantiate WebRTC (and show start button)
ctx = webrtc_streamer(
    key="FaceIDAppDemo",
    mode=WebRtcMode.SENDONLY,
    media_stream_constraints={"video": True, "audio": False},
    rtc_configuration={"iceServers": [{"urls": ["stun:stun.l.google.com:19302"]}]},
    video_receiver_size=1,
    async_processing=True,
)

# Live Stream Display
image_loc = st.empty()

if ctx.video_receiver:
    while True:
        try:
            frame = ctx.video_receiver.get_frame(timeout=1)
            img = frame.to_ndarray(format="rgb24")
        except:
            continue

        # Display Live Frame
        image_loc.image(img)

```

, which is running fine locally. But on Streamlit Cloud, after I press start, it seems to get a connection to the webcam (the text turns to "Stop", but after a few seconds the text turns back to "Start". In the logs, my app got stuck at "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False."

Do you have any suggestions, on what I could have done wrong here? Or where the error is? 

Thank you, 
Cheers, 
Martlgap

**Comment by Martlgap** [comment]
Found the error: 

In [https://github.com/whitphx/streamlit-webrtc/blob/64885865cf076bd78a0ed8f0af99426f71402276/sample_utils/turn.py](https://github.com/whitphx/streamlit-webrtc/blob/64885865cf076bd78a0ed8f0af99426f71402276/sample_utils/turn.py)

is written:

""" Use Twilio's TURN server because Streamlit Community Cloud has changed
 its infrastructure and WebRTC connection cannot be established without TURN server now. """

So I guess the former solution with a free STUN server from google is not working anymore. 

Using a twilio TURN server, my app is working now.

**Comment by takan1** [comment]
@Martlgap Same issue for me. Could you provide me with the twilio TURN server code part?
