### ISSUE TITLE
Does this support multi camera

### ISSUE THREAD

**Issue by cailurus** [whitphx/streamlit-webrtc#1334]

**Comment by whitphx** [comment]
[This sample](https://github.com/whitphx/streamlit-webrtc/blob/main/pages/6_mix_multi_inputs.py) may help which shows how to merge (mix) multiple camera inputs into one video stream and display it.

**Comment by cailurus** [comment]
Cool, I followed this and it's working as I expected. Thanks for the great work @whitphx !
