### ISSUE TITLE
Non of the samples and demos work! The video/audio stuck loading forever. 

### ISSUE THREAD

**Issue by takan1** [whitphx/streamlit-webrtc#1608]
Pardon me if the project is not maintained currently but it seems like all the samples and demos are broken and cannot load video or audio. I'm using a Mac M3 with Chrome. Anyone help?

**Comment by whitphx** [comment]
Confirmed the problem. Thank you for reporting it.
Will take a look.

**Comment by zachlee10** [comment]
The same problem. Windows + edge +vscode, even the simplest demo cannot be run. 
<img width="400" alt="Untitled" src="https://github.com/whitphx/streamlit-webrtc/assets/17738709/6ce497c2-ce9e-4009-8790-3c45d54bc496">

**Comment by whitphx** [comment]
Now it should be fixed.
The problem was solved by #1627 and the deployed version was upgraded to the latest one including this patch.
Thank you for reporting this!
