### ISSUE TITLE
1 input to N outputs

### ISSUE THREAD

**Issue by whitphx** [whitphx/streamlit-webrtc#165]
For example, 1 input from a single camera, 2 outputs including a raw preview and a transformed stream.

**Comment by yaamas** [comment]
Raw preview can be the input stream and the transformed stream is already there. This is what I did to save on bandwidth,

**Comment by whitphx** [comment]
Your idea requires JS coding for each application and is not possible, or not flexible enough even if possible, within Streamlit architecture.
What is useful with Stremalit is Python-only coding, and it's same as streamlit-webrtc - with this component, developers can implement the transform only with the Python code and this design requires sending back video from the server to the client.
So, in the case of streamlit-webrtc, bandwidth savings are not the priority. It aims simple design and easy use for developers.
If developers want to create efficient applications, they should write tailor-made server-side and frontend code without Streamlit and streamlit-webrtc.

**Comment by joe733** [comment]
This (1 input to n output) works with `transform()`

```python
import cv2 as cv
from streamlit_webrtc import VideoTransformerBase, webrtc_streamer


class VideoTransformer(VideoTransformerBase):

    def transform(self, frame):
        img = frame.to_ndarray(format='bgr24')
        img = cv.cvtColor(cv.Canny(img, 100, 200), cv.COLOR_GRAY2BGR)
        return img


webrtc_streamer(key='Test')
webrtc_streamer(key='Test2', video_transformer_factory=VideoTransformer)
```

![image](https://user-images.githubusercontent.com/38415384/119431391-1e568a80-bd30-11eb-8b37-c7f6b73382dc.png)

but when I replace `transform()` with `recv()` like so

```python
...
  def recv(self, frame):
        img = frame.to_ndarray(format='bgr24')
        img = cv.cvtColor(cv.Canny(img, 100, 200), cv.COLOR_GRAY2BGR)
        return img
...
```

I get this warning:

```text
Your app is having trouble loading the streamlit_webrtc.webrtc_streamer component.

(The app is attempting to load the component from **, and hasn't received its "streamlit:componentReady"** message.)

    - If this is a development build, have you started the dev server?
    - If this is a release build, have you compiled the frontend?

For more troubleshooting help, please see the Streamlit Component docs or visit our forums.
```

![error](https://i.stack.imgur.com/7qTbx.png)

**Comment by whitphx** [comment]
> This (1 input to n output) works with transform()

That is not 1-to-N setup, but just double 1-to-1 connections which have 2 up-streams and 2 down-streams.
What this issue means is something like below which have 1 up-stream and 2 down-stream.
```python
ctx_loopback = webrtc_streamer(key="loopback", mode=WebRtcMode.SENDRECV)
ctx_transformed =  webrtc_streamer(key="transform", mode=WebRtcMode.SENDONLY, input=ctx_loopback)
```

> I get this warning:

mm, it looks weird since the problem occurs on the frontend though the difference is only on the server-side code (`recv()` and `transform()`).
Can you share the complete code including all `*.py` and `requirements.txt` to reproduce the bug?

>  Why does recv() call transform() if ti's depreciated 🤔 ?

It's not related to this issue.
Anyway, it's for backward compatibility for users since older versions. `recv()` will be removed in version 1.0.

> I manage to use recv() like this:

It's also not about this issue though, anyway, the returned value of `recv()` is different from `transform()`'s one. It must return an instance of `av.VideoFrame` or `av.AudioFrame`, not `np.ndarray`. See the sample `app.py`.

**Comment by joe733** [comment]
> That is not 1-to-N setup, but just double 1-to-1 connections which have 2 up-streams and 2 down-streams.

Oh I see...

> Can you share the complete code including all *.py and requirements.txt to reproduce the bug?

Sure it's not related to this issue, so opening `discussions` tab (for this repository) would be convenient. Here's my final year project https://github.com/joe733/vudoku which uses `streamlit-webrtc`. Gotta do a presentation this week with minimum working example but I'm stuck 😢 

> Anyway, it's for backward compatibility for users since older versions. `recv()` will be removed in version 1.0.

Did you mean `transform()` will be removed in `v1.0`?

> The returned value of recv() is different from transform()'s one. It must return an instance of av.VideoFrame or av.AudioFrame, not np.ndarray. See the sample app.py.

Okay, let me see how to apply it in my use case, little bit confused there.

> Discussion tab will be really helpful. Thanks a lot!

**Comment by whitphx** [comment]
I opened the discussions 👍 

> Did you mean transform() will be removed in v1.0?

Yes.

**Comment by whitphx** [comment]
* `MediaRelay` can be used for this purpose
* Multiple `WebRtcWorker` instances must share the event loop -> exposing the relayed stream tracks is not enough.
