### ISSUE TITLE
Running deep learning models using a variety of media sources

### ISSUE THREAD

**Issue by hellodoksa** [whitphx/streamlit-webrtc#202]
Hi @whitphx 
Thank you for your great work! streamlit-webrtc 😀

I want to run my custom deep learning models using a variety of media sources
For example, I want to run my YOLO model using the RTSP camera.

By modifying [this function](https://github.com/whitphx/streamlit-webrtc-example/blob/2d1d8386fcb424a7d24e326386886293d54db1cd/app.py#L297), I did run the model I trained
However, I could not use other media sources. It worked only on Webcam
I don't know how to change it to another media source.

Could you explain that function(app_object_detection()) with an example?
What should I change within this function

It is difficult for me to understand just by the explanation above.
I wish you could help me.
Thank you.

**Comment by whitphx** [comment]
Hi, thank you for the message.

Currently media sources like RTSP are not supported, and this is what #145 is referring to.
Please track #145 , and I will close this issue for now.

**Comment by whitphx** [comment]
You can use local cameras and RTSP streams as media sources and apply video filters to them. See the sample in #145.
