### ISSUE TITLE
Problem with RECVONLY reconnections

### ISSUE THREAD

**Issue by marcoslucianops** [whitphx/streamlit-webrtc#205]
Hi, when I stop and start video files/streams, using RECVONLY, it doesn't work. It starts the video correctly, but when I stop and start again, it shows only a gray screen.

The log is:
```
2021-05-17 12:27:14.093 ICE connection state is closed
2021-05-17 12:27:15.780 Connection(42) Remote candidate "0163614b-42ff-4b75-925c-80a5e26dddb6.local" resolved to 192.168.1.13
2021-05-17 12:27:15.986 Connection(42) Check CandidatePair(('192.168.1.13', 56258) -> ('192.168.1.13', 59948)) State.FROZEN -> State.WAITING
2021-05-17 12:27:15.986 Connection(42) Check CandidatePair(('172.17.0.1', 60268) -> ('192.168.1.13', 59948)) State.FROZEN -> State.WAITING
2021-05-17 12:27:15.987 ICE connection state is checking
2021-05-17 12:27:15.987 Connection(42) Check CandidatePair(('192.168.1.13', 56258) -> ('192.168.1.13', 59948)) State.WAITING -> State.IN_PROGRESS
2021-05-17 12:27:16.028 Connection(42) Check CandidatePair(('172.17.0.1', 60268) -> ('192.168.1.13', 59948)) State.WAITING -> State.IN_PROGRESS
2021-05-17 12:27:16.031 Connection(42) Check CandidatePair(('192.168.1.13', 56258) -> ('192.168.1.13', 59948)) State.IN_PROGRESS -> State.SUCCEEDED
2021-05-17 12:27:16.032 Connection(42) Check CandidatePair(('172.17.0.1', 60268) -> ('192.168.1.13', 59948)) State.IN_PROGRESS -> State.SUCCEEDED
```

![image](https://user-images.githubusercontent.com/47423225/118515092-70355a00-b70b-11eb-8cd3-e13b1e9f3195.png)

How can I solve it?

**Comment by marcoslucianops** [comment]
In console I get this error
```
Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
```

**Comment by whitphx** [comment]
Hi, thank you for the report!

**Comment by marcoslucianops** [comment]
Hi, I found another similar bug, when I navigate to another page and come back to the player page, same error occurs

```
Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
```

**Comment by whitphx** [comment]
@marcoslucianops Hi, thank you, but I could not reproduce the bug with the latest version ( https://share.streamlit.io/whitphx/streamlit-webrtc-example/main/app.py ).
Can you tell me the details? For example,
* What browser and OS are you using?
* Which versions of Streamlit and `streamlit-webrtc` are you using?
* Which version of the app. are you using, hosted one on the Streamlit Sharing or running in your local env?
  * If local env, what is the Git revision of the app?
* Which page did you navigate to after the player page?
* On that page, did you play the stream before getting back to the player page?
* Which file did you play on the player page?
* Did you do something before going to the player page?

**Comment by marcoslucianops** [comment]
I'm using Chrome.
Latest streamlit and streamlit-webrtc versions.
I navigate to another player page, but with different component key.
I play rtsp streams in each player.
I just select another page with another player and, when I back to previous page, I get this error.

**Comment by whitphx** [comment]
I cannot reproduce it.
Can you share the complete code including `*.py` files and `requirements.txt` which reproduces the bug?

> Latest streamlit and streamlit-webrtc versions.

`streamlit==0.82.0` and `streamlit_webrtc==0.20.1`?

> I play rtsp streams in each player.

Does this mean you use streamlit-webrtc component with RECVONLY mode (streamlit-webrtc does not use RTSP though)?

**Comment by marcoslucianops** [comment]
I'm not using the streamlit anymore. I was using one player in each page only for read rtsp streams.

**Comment by whitphx** [comment]
mm, what do you mean?
Is there something related to this issue or this component even though you are not using Streamlit?
Can you share the entire code that reproduces the bug you reported?

**Comment by marcoslucianops** [comment]
My python code [web.txt](https://github.com/whitphx/streamlit-webrtc/files/6650314/web.txt)

**Comment by whitphx** [comment]
It does not work with error

> NameError: name 'default_board_name' is not defined

When I set an arbitrary string as `default_board_name` like `default_board_name = "foo"`,
another error has shown.

> OperationalError: no such table: streams

**Comment by marcoslucianops** [comment]
Sorry I forgot the default_board_name.
About the second error, its due sqlite. I was using a sqlite database to read values.
Use: [files.zip](https://github.com/whitphx/streamlit-webrtc/files/6671447/files.zip)

Note: I don't have the streamlit installed anymore. Please check if these files are correct.

**Comment by whitphx** [comment]
It still did not work, then I fixed
```diff
-        state.running = stream[5]
+        state.running = stream[1]
```

**Comment by whitphx** [comment]
The screen has finally been shown, but the app seems not to work correctly as the screen is stuck with a message "Connecting to: ..." and no player appears after I enter RTSP URL.
I cannot hang on debugging this script.
Please reopen this issue if you find this issue again.

**Comment by marcoslucianops** [comment]
I installed the streamlit and fixed the code. Check now please.
Steps: add one stream, run the stream, add another stream, run stream, go back to first stream and you will get the error.

Files: [files.zip](https://github.com/whitphx/streamlit-webrtc/files/6672002/files.zip)

**Comment by whitphx** [comment]
Hi, I found a bug and fixed it in v0.22.1. Please check it.

**Comment by whitphx** [comment]
This problem had been introduced in 0.84.1 (or 0.84.0)

**Comment by okhomin** [comment]
Hello @whitphx,

Thank you so much for this great library!
I think the bug is back.
Reproduction strep:
1. Add `desired_playing_state=True` to `webrtc_streamer` in [14_programmable_source.py](https://github.com/whitphx/streamlit-webrtc-example/blob/main/pages/14_programmable_source.py).
```
webrtc_streamer(
    key="player",
    mode=WebRtcMode.RECVONLY,
    source_video_track=video_source_track,
    media_stream_constraints={"video": True, "audio": False},
    desired_playing_state=True,
    on_change=on_change,
)
```
2. Run the program with `streamlit run app.py`
3. Navigate to the `programmable source` page.
4. The camera opens without any errors.
5. Click on any other page and return back to the `programmable source` page.
6. The camera will return an error as it's shown in the screenshot.
<img width="1145" alt="Screenshot 2023-12-25 at 8 39 38 PM" src="https://github.com/whitphx/streamlit-webrtc/assets/37224169/c691d5eb-a558-4e23-97ad-ef14d420de6c">
