### ISSUE TITLE
Adjusting Size of Webcam Video

### ISSUE THREAD

**Issue by jasonchanhku** [whitphx/streamlit-webrtc#226]
Hi @whitphx , first and foremost, thanks for this amazing component of Streamlit and your contributions. I would like to ask if there is a way to adjust the webcam video sizes after clicking "start"? As I switched into a large monitor and the video size seems to have quadrupled. I appreciate your feedback on this. Thanks

Regards and thanks.

**Comment by jasonchanhku** [comment]
I experimented myself on some things and below are my findings:

- the frame returned is always the same  (by checking the frame's ndarray shape)
- current workaround is I currently manually change the value of k={width:"100%"} in the main.e8ebcbb7.chunk.js file

Thanks.

**Comment by whitphx** [comment]
The input camera resolution is not changed (as you may know from that the frame sizes are always the same) and the rendered video element width is adjusted to outer frame of the Streamlit app (this is controlled via the "100%" specification you found).
However it sounds a little bit weird as I think this behavior is same as other Streamlit components. How do you see other components like `st.slider`, `st.text_input`, `st.textarea`, or `st.DataFrame` on your high-res screen?. Is only this component's appearance strange?

**Comment by jasonchanhku** [comment]
Thanks for your response. Let me further investigate this and get back to you.

**Comment by jasonchanhku** [comment]
Finally figured it out. I didn't realize i had `layout=wide` in `st.set_page_config()`. Setting is back to `centered` fixed it. Apologies for the inconvenience caused. Thanks for the prompt response! Appreciate it!
