### ISSUE TITLE
Show emotion result in other window

### ISSUE THREAD

**Issue by balavenkatesh3322** [whitphx/streamlit-webrtc#240]
Instead of showing all the responses in the frame, I want to show in separately.  how to send all values in response and show it in the browser.

**Comment by whitphx** [comment]
Which do you mean in the following?
* You want to show the metadata like predicted labels as texts or tables: Then follow the way of the object detection demo in [`app.py`](https://github.com/whitphx/streamlit-webrtc/blob/master/app.py) does. It shows the labels with `st.table`
* You want to show another video window: It is not supported now, and is a part of #165. Please track that issue.

**Comment by balavenkatesh3322** [comment]
@whitphx Thanks for the quick response. 

Your first points help me a lot. I really want the same functionality but I would like to show the history of all the results. once the stream starts we have to start showing the results until the video stream ends we have to show all the predicted results in the table.

**Comment by whitphx** [comment]
You can simply customize the code to hold every `result` over the iterations;
https://github.com/whitphx/streamlit-webrtc/blob/3ace08de428af2be262219fd248560371346bf6d/app.py#L422-L432
What's the problem?

**Comment by balavenkatesh3322** [comment]
Thanks for pointing out the code. I got it .

Thanks.
