### ISSUE TITLE
How to configure HTTPS in EC2 server

### ISSUE THREAD

**Issue by balavenkatesh3322** [whitphx/streamlit-webrtc#241]
I would like to deploy this app into the AWS server but the application requires HTTPS protocol to stream video. How to configure HTTPS in streamlit application. by default, it takes HTTP protocol.

**Comment by whitphx** [comment]
It's not `streamlit-webrtc`'s issue.

[This part of the tutorial](https://dev.to/whitphx/build-a-web-based-real-time-computer-vision-app-with-streamlit-57l2#https) might be a good first read though.
