### ISSUE TITLE
Connection(0) Remote candidate "xxxxxxxxxx.local" could not be resolved

### ISSUE THREAD

**Issue by P3RI9** [whitphx/streamlit-webrtc#277]
Hi! Im trying to use your library for real time video streaming with streamlint. I'm facing an error with Ice Servers connection that I can't resolve. Could you please help me? 

Code:

```
    media_file_info = {
        'local_file_path':tfile.name,
        'type':'video'
    }
    
    WEBRTC_CLIENT_SETTINGS = ClientSettings()
    WEBRTC_CLIENT_SETTINGS.update(
        {
            "media_stream_constraints": {
                "video": media_file_info["type"] == "video",
                "audio": media_file_info["type"] == "audio",
            }
        }
    )
    frame_rate = 30
    WEBRTC_CLIENT_SETTINGS.update(
        ClientSettings(
            media_stream_constraints={
                "video": {"frameRate": {"ideal": frame_rate}},
            },
        )
    )
    webrtc_ctx = webrtc_streamer(
        key="media-streaming",
        mode=WebRtcMode.RECVONLY,
        client_settings=WEBRTC_CLIENT_SETTINGS,
        player_factory=create_player,
        video_processor_factory=OpenCVVideoProcessor,
    )

    tfile.close()
    os.unlink(tfile.name)
```

Error:
![image](https://user-images.githubusercontent.com/24256295/123951369-9e5db900-d99c-11eb-9bfb-02b6bc6a9180.png)

**Comment by whitphx** [comment]
That kind of local IP addresses, `<UUID>.local`, is created through mDNS (Mutlicast DNS) for security sake.
This is a nice mechanism to prevent your real local IP addresses being stolen by remote services outside your LAN through WebRTC connection.
For the details, google keywords like "mDNS WebRTC", or see articles like https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/

So, you should keep mDNS enabled when you use WebRTC services hosted on public networks, however, it is sometimes inconvenient like this case.
Then, you can disable mDNS as workaround.
https://stackoverflow.com/questions/61629450/webrtc-does-not-work-in-the-modern-browsers-when-a-peer-is-not-behind-a-nat-beca explains the solution.
> In Chrome, by disabling Anonymize local IPs exposed by WebRTC in "about:flags" page. In Firefox, by setting false media.peerconnection.ice.obfuscate_host_addresses in "about:config" page.)

Note that this solution is an instant workaround and fundamentally you should keep mDNS enabled and set up mDNS resolver for the server-side to be able to deal with the mDNS addresses.
