### ISSUE TITLE
Removing controls

### ISSUE THREAD

**Issue by galleon** [whitphx/streamlit-webrtc#302]
Thanks for this great component !
I am trying to implement in `streamlit` an authentication using the webcam.
I was wondering if it was possible to get rid of the controls below:

![image](https://user-images.githubusercontent.com/259772/124492459-c8581680-ddb4-11eb-9adf-5c7056ff15fb.png)

**Comment by whitphx** [comment]
* The start/stop button is removed when you set `desired_playing_state` argument. See the "Control the playing state programatically" example.
* "Select device" button is removed when you use this component with RECVONLY mode.

Further controls are not supported.

**Comment by galleon** [comment]
Thanks for the info. That's cristal clear.
