### ISSUE TITLE
Support for seek forward when playing a video file

### ISSUE THREAD

**Issue by ajaichemmanam** [whitphx/streamlit-webrtc#360]
Is it possible to seek forward in a video file during or before streaming?

**Comment by whitphx** [comment]
I think it's impossible.
streamlit-webrtc is a sort of aiortc's wrapper and its video player is simply using [aiortc's `MediaPlayer` class](https://aiortc.readthedocs.io/en/latest/helpers.html#aiortc.contrib.media.MediaPlayer), which does not support seeking.
