### ISSUE TITLE
can't find streamlit_webrtc/frontend/build

### ISSUE THREAD

**Issue by lixiepeng** [whitphx/streamlit-webrtc#399]
```
streamlit.errors.StreamlitAPIException: No such component directory: 'streamlit-webrtc/streamlit_webrtc/frontend/build'
```

**Comment by whitphx** [comment]
Please provide more information to reproduce the error.

**Comment by lixiepeng** [comment]
> Please provide more information to reproduce the error.
> 
> Are you running your app script under the directory where this repository is cloned to or included in the `sys.path`?

it works when run out of repository.

**Comment by karryor** [comment]
Hello, have you solved this problem? How to do it?
