### ISSUE TITLE
mediaDevices is not found

### ISSUE THREAD

**Issue by lixiepeng** [whitphx/streamlit-webrtc#402]
```
Error: navigator.mediaDevices is undefined. It seems the current document is not loaded securely.
```

**Comment by whitphx** [comment]
Does this help? https://dev.to/mute/comment/1gj25

**Comment by murtazabasu** [comment]
It works properly when the `serverAddress` is set to **localhost** in the `config.toml` file.
However it throws the above error as mentioned by @whitphx when it is made to run on network url.

**Comment by whitphx** [comment]
It's normal. Did you read https://dev.to/whitphx/build-a-web-based-real-time-computer-vision-app-with-streamlit-57l2#https as linked from the page above?

**Comment by whitphx** [comment]
@murtazabasu Thank you.

**Comment by nguyentu20398** [comment]
@whitphx I also meet this error, I also use https but the website just loading. Can you explain for me?
