### ISSUE TITLE
USB cam not detected with Raspberry pi 3

### ISSUE THREAD

**Issue by lalmiAhmed** [whitphx/streamlit-webrtc#442]
I am facing an issue when running any of the hosted examples in my raspberry pi 3 with USB webcam
"NotFoundError: Requested device not found"

the USB cam works fine on my laptop.

**Comment by whitphx** [comment]
I can't help with only that info, and don't know any potential issues.

As I googled with that error message, it seems that the error comes from outside this component, probably depending on the RasPi env.
