### ISSUE TITLE
Launch without internet connection

### ISSUE THREAD

**Issue by ioangatop** [whitphx/streamlit-webrtc#485]
Hi and thank you for open-sourcing this amazing component! 
I would like to ask if it is possible to launch the service without internet connection (see https://github.com/aiortc/aiortc/issues/524)

**Comment by whitphx** [comment]
Do you mean the situation where both the client and the server are on the same host (localhost) without the Internet connection?
It worked at least in my environment, but I think it depends on browsers or other stuff as answered in the thread. WebRTC connection is dealt with by the browser's API (client-side) and aiortc (server-side) implementations.

**Comment by ioangatop** [comment]
Yes exactly, but it doesn't seem to work with my machine. If I have any updates I'll post them here!
