### ISSUE TITLE
Rtsp 

### ISSUE THREAD

**Issue by Hiwyl** [whitphx/streamlit-webrtc#514]
Rtsp stream at the stop page after the background or in the execution，unless ctrl +c in cmd

**Comment by whitphx** [comment]
?

**Comment by Hiwyl** [comment]
RTSP detection can't stop，only ctrl+c

**Comment by whitphx** [comment]
Understood, thanks.

**Comment by whitphx** [comment]
#533 will solve this problem partially. RTSP process will be stopped when users terminate the WebRTC sessions.

**Comment by Hiwyl** [comment]
get,TKS

**Comment by whitphx** [comment]
Fixed in v0.32.0
