### ISSUE TITLE
cannot import name 'AudioProcessorBase' from 'streamlit_webrtc'

### ISSUE THREAD

**Issue by spectereye** [whitphx/streamlit-webrtc#549]
Hi, when try demo below get exception:

$ pip install streamlit-webrtc opencv-contrib-python matplotlib pydub
$ streamlit run https://raw.githubusercontent.com/whitphx/streamlit-webrtc-example/main/app.py

2021-12-02 11:10:04.006 Traceback (most recent call last):
  File "C:\Python\lib\site-packages\streamlit\script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\xxxx\AppData\Local\Temp\tmpi_0esfbc\app.py", line 22, in <module>
    from streamlit_webrtc import (
ImportError: cannot import name 'AudioProcessorBase' from 'streamlit_webrtc' (C:\Python\lib\site-packages\streamlit_webrtc\__init__.py)

C:\Users\xxxx>pip list | grep pydub
pydub                         0.25.1

any guide please?

**Comment by whitphx** [comment]
Which version of `streamlit-webrtc` is loaded? (See the output of `python -c "import streamlit_webrtc; print(streamlit_webrtc.__version__)"`)

**Comment by spectereye** [comment]
Thanks @whitphx, just checked, my fault, i ues `pip install  streamlit-webrtc` without --upgrade ... after upgrade, everything works now!
