### ISSUE TITLE
'SessionInfo' object has no attribute 'report_run_count'

### ISSUE THREAD

**Issue by AntonioTannoury** [whitphx/streamlit-webrtc#709]
Hello, I'm just doing a simple project on face detection and found your approach on live streaming the video from the users device (Amazing solution btw!)
I followed your suggestion by using streamlit share server to avoid the complexities faced in going though colab->ngrok->TURN server.
For now, my app just consists of opening the camera under the following script recommended in the documentation (of course followed by the installation of streamlit-webstr):
#
from streamlit_webrtc import webrtc_streamer
webrtc_streamer(key="sample")
#
But it's giving the following error: 
"""AttributeError: 'SessionInfo' object has no attribute 'report_run_count'"""

**Comment by code-farzi-baniya** [comment]
Hi Antonio, I had faced the same problem as you did! In my case, I was using a virtual environment and trying to run my app on it. I was bombarded with the same error on it but when I switched my environment to the global one for my system(mac); the code started working just fine for me. Try the same and let me know

**Comment by alercelik** [comment]
Hi, I got the same problem and solved by downgrading streamlit to 1.5.1
`pip install streamlit==1.5.1`

I think streamlit just released the version 1.6.0

**Comment by corticalstack** [comment]
@alercelik thanks, that solved same issue for me!

**Comment by whitphx** [comment]
Thank you for the report.
I will check the changes on v1.6.

**Comment by whitphx** [comment]
Development notes:

`SessionInfo.report_run_count` [has been renamed to `Sessioninfo.script_run_count`](https://github.com/streamlit/streamlit/commit/e9e199587c65940b338de7233b661646793350a1#diff-c77be03a88a42eb1cc73b974b116704e1582ff5696666d4920af210b72c2b542R138), and it has been released in `1.6.0`.
(The Git tag info shows this change has been introduced in `1.5.1`, but the tag info on `1.5.1` seems wrong and it is not actually released. See https://github.com/streamlit/streamlit/issues/4462).

**Comment by whitphx** [comment]
This will be fixed with `streamlit-webrtc==0.35.2`
