### ISSUE TITLE
Specify a Local Port for Binding

### ISSUE THREAD

**Issue by alercelik** [whitphx/streamlit-webrtc#738]
Is there a way to specify a port to bind for webrtc? I can use only one port however I believe aiortc assigns a port randomly and I couldn't find a way to specify a local port.

**Comment by whitphx** [comment]
From my understanding, there is no way to do it. See #7.

If you are talking about Docker, https://github.com/whitphx/streamlit-webrtc/issues/7#issuecomment-1001866337 may help you.

**Comment by alercelik** [comment]
Oh, I missed that issue. Thanks!
