### ISSUE TITLE
Setting Log Level

### ISSUE THREAD

**Issue by alercelik** [whitphx/streamlit-webrtc#752]
Hello, how can I set log level? I want to set it to WARNING for this library and INFO for my own program.

**Comment by whitphx** [comment]
This library uses a logger with name `streamlit_webrtc` or its child loggers.
The code below is a sample to get the logger and set the log level.
https://github.com/whitphx/streamlit-webrtc/blob/b80878229378a090510851f32c400234da60523b/app.py#L684-L685

**Comment by whitphx** [comment]
Added the "logging" section in README:
https://github.com/whitphx/streamlit-webrtc#logging
