### ISSUE TITLE
streamlit.errors.StreamlitAPIException 

### ISSUE THREAD

**Issue by suyashhchougule** [whitphx/streamlit-webrtc#836]
followed instruction to run  `$ streamlit run app.py` but getting this error 
 `streamlit.errors.StreamlitAPIException: No such component directory: '/home/suyash/Desktop/streamlit-webrtc/streamlit_webrtc/frontend/build'`

**Comment by whitphx** [comment]
https://github.com/whitphx/streamlit-webrtc/issues/399#issuecomment-909815583
