### ISSUE TITLE
Can we add mjpeg as input instead of webcam or camera 

### ISSUE THREAD

**Issue by tomriddle54** [whitphx/streamlit-webrtc#909]
@whitphx Hello, we are using cctv camera feed which is in the from of RTSP and converting it to MJPEG for browser view is there any way we can use streamlit-webrtc or modify it.

**Comment by whitphx** [comment]
There is an example to use RTSP source: https://github.com/whitphx/streamlit-webrtc/blob/0b143be13ec71c3339e4a1917aab8d4fd7dd333f/app.py#L415
while I'm not sure if it's possible to use MJPEG in that way.
