### ISSUE TITLE
Component Error

### ISSUE THREAD

**Issue by geksogen** [whitphx/streamlit-webrtc#960]
Hello, when i use webrtc on change “My Device” on my application , have this problem “Component Error”. This problem wos testing on other browsers. Help help please :slight_smile:

Streamlit, version 1.10.0
Streamlit-webrtc  0.42.0

********************************************

`import streamlit as st
from streamlit_webrtc import webrtc_streamer

st.title("My first Streamlit app")
st.write("Hello, world")

webrtc_streamer(key="example")`

**Comment by whitphx** [comment]
> when i use webrtc on change “My Device” on my application
What does it mean...?

And the error logs on the console may also help.
