### ISSUE TITLE
Camera can‘t work

### ISSUE THREAD

**Issue by Inbloom9** [whitphx/streamlit-webrtc#964]
Thank for your streamlit-webrtc, it's a good job. But i have something wrong with it.  The camera can't work well when I test  your demos with my PC and mobile devices. I find some people have the same problem with me, but I still haven‘t find a good solution, do you have some new method  to solve it？

**Comment by whitphx** [comment]
https://github.com/whitphx/streamlit-webrtc/issues/852#issuecomment-1139837756
https://github.com/whitphx/streamlit-webrtc/issues/552#issuecomment-1108781763
help?
